export enum IconType {
  GITHUB = 'github',
  LINKEDIN = 'linkedin',
  CODEPEN = 'codepen',
  STACKOVERFLOW = 'stackoverflow',
  GMAIL = 'gmail',
  GATSBY = 'gatsby',
  PHP = 'php',
  WORDPRESS = 'wordpress',
  ANGULAR = 'angular',
  REACT = 'react',
  CSS = 'css',
  HTML = 'html',
  DOCKER = 'docker',
  K8S = 'k8s',
  RUBY = 'ruby',
  JEST = 'jest',
  PYTHON = 'python',
  JAVASCRIPT = 'javascript',
  REDUX = 'redux',
  TYPESCRIPT = 'typescript',
  GIT = 'git',
  STORYBOOK = 'storybook',
  CIRCLECI = 'circleci',
  STYLEDCOMPONENTS = 'styledcomponents',
}
