name: Deploy Surge Website
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g yarn
      - run: yarn
      - run: yarn test
      - name: Build Storybook
        run: yarn build-storybook
      - name: Install Surge
        run: npm install --global surge
      - name: Run surge
        run: npx surge ./storybook-static graffft-waggle.surge.sh --token ${{ secrets.SURGE_TOKEN }}
